- name: Deploy Docker Compose app
  hosts: remote
  tasks:
    # - name: Transfer docker-compose.yml
    #   copy:
    #     src: ./docker-compose.yml
    #     dest: /home/deploy/docker-compose.yml

    # - name: Transfer any other necessary files or directories
    #   copy:
    #     src: ../showcase
    #     dest: /home/deploy/app

    - name: Transfer any other necessary files or directories
      synchronize:
        src: ./
        dest: /home/deploy/app
        recursive: yes
        rsync_opts:
          - "--exclude=.git/"
          
    - name: Start the Docker Compose services
      command: docker-compose up -d
      args:
        chdir: /home/deploy/app